export const SAVE_ITEM_REQUEST = 'SAVE_ITEM_REQUEST';
export const SAVE_ITEM_SUCCESS = 'SAVE_ITEM_SUCCESS';
export const SAVE_ITEM_FAILURE = 'SAVE_ITEM_FAILURE';

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';

export const FIND_ITEM_REQUEST = 'FIND_ITEM_REQUEST';
export const FIND_ITEM_SUCCESS = 'FIND_ITEM_SUCCESS';
export const FIND_ITEM_FAILURE = 'FIND_ITEM_FAILURE';

export const FIND_ITEMS_REQUEST = 'FIND_ITEMS_REQUEST';
export const FIND_ITEMS_SUCCESS = 'FIND_ITEMS_SUCCESS';
export const FIND_ITEMS_FAILURE = 'FIND_ITEMS_FAILURE';

export const SAVE_TRANSACTION_REQUEST = 'SAVE_TRANSACTION_REQUEST';
export const SAVE_TRANSACTION_SUCCESS = 'SAVE_TRANSACTION_SUCCESS';
export const SAVE_TRANSACTION_FAILURE = 'SAVE_TRANSACTION_FAILURE';

export const DELETE_TRANSACTION_REQUEST = 'DELETE_TRANSACTION_REQUEST';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAILURE = 'DELETE_TRANSACTION_FAILURE';

export const FIND_TRANSACTION_REQUEST = 'FIND_TRANSACTION_REQUEST';
export const FIND_TRANSACTION_SUCCESS = 'FIND_TRANSACTION_SUCCESS';
export const FIND_TRANSACTION_FAILURE = 'FIND_TRANSACTION_FAILURE';

export const FIND_TRANSACTIONS_REQUEST = 'FIND_TRANSACTIONS_REQUEST';
export const FIND_TRANSACTIONS_SUCCESS = 'FIND_TRANSACTIONS_SUCCESS';
export const FIND_TRANSACTIONS_FAILURE = 'FIND_TRANSACTIONS_FAILURE';

export const SUMMARY_TRANSACTIONS_REQUEST = 'SUMMARY_TRANSACTIONS_REQUEST';
export const SUMMARY_TRANSACTIONS_SUCCESS = 'SUMMARY_TRANSACTIONS_SUCCESS';
export const SUMMARY_TRANSACTIONS_FAILURE = 'SUMMARY_TRANSACTIONS_FAILURE';

export const DELETE_STOCK_REQUEST = 'DELETE_STOCK_REQUEST';
export const DELETE_STOCK_SUCCESS = 'DELETE_STOCK_SUCCESS';
export const DELETE_STOCK_FAILURE = 'DELETE_STOCK_FAILURE';

export const SAVE_STOCK_REQUEST = 'SAVE_STOCK_REQUEST';
export const SAVE_STOCK_SUCCESS = 'SAVE_STOCK_SUCCESS';
export const SAVE_STOCK_FAILURE = 'SAVE_STOCK_FAILURE';

export const FIND_STOCK_REQUEST = 'FIND_STOCK_REQUEST';
export const FIND_STOCK_SUCCESS = 'FIND_STOCK_SUCCESS';
export const FIND_STOCK_FAILURE = 'FIND_STOCK_FAILURE';

export const FIND_STOCKS_REQUEST = 'FIND_STOCKS_REQUEST';
export const FIND_STOCKS_SUCCESS = 'FIND_STOCKS_SUCCESS';
export const FIND_STOCKS_FAILURE = 'FIND_STOCKS_FAILURE';

export const SUMMARY_STOCKS_REQUEST = 'SUMMARY_STOCKS_REQUEST';
export const SUMMARY_STOCKS_SUCCESS = 'SUMMARY_STOCKS_SUCCESS';
export const SUMMARY_STOCKS_FAILURE = 'SUMMARY_STOCKS_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const OAUTH_REQUEST = 'OAUTH_REQUEST';
export const OAUTH_FAILURE = 'OAUTH_FAILURE';
export const OAUTH_SUCCESS = 'OAUTH_SUCCESS';

export const FIND_PARTNER_REQUEST = 'FIND_PARTNER_REQUEST';
export const FIND_PARTNER_SUCCESS = 'FIND_PARTNER_SUCCESS';
export const FIND_PARTNER_FAILURE = 'FIND_PARTNER_FAILURE';

export const SAVE_USER_REQUEST = 'SAVE_USER_REQUEST';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAILURE = 'SAVE_USER_FAILURE';

export const FIND_USER_REQUEST = 'FIND_USER_REQUEST';
export const FIND_USER_SUCCESS = 'FIND_USER_SUCCESS';
export const FIND_USER_FAILURE = 'FIND_USER_FAILURE';

export const FIND_USERID_REQUEST = 'FIND_USERID_REQUEST';
export const FIND_USERID_SUCCESS = 'FIND_USERID_SUCCESS';
export const FIND_USERID_FAILURE = 'FIND_USERID_FAILURE';

export const SAVE_RENT_REQUEST = 'SAVE_RENT_REQUEST';
export const SAVE_RENT_SUCCESS = 'SAVE_RENT_SUCCESS';
export const SAVE_RENT_FAILURE = 'SAVE_RENT_FAILURE';

export const FIND_RENTS_REQUEST = 'FIND_RENTS_REQUEST';
export const FIND_RENTS_SUCCESS = 'FIND_RENTS_SUCCESS';
export const FIND_RENTS_FAILURE = 'FIND_RENTS_FAILURE';

export const FIND_RENT_REQUEST = 'FIND_RENT_REQUEST';
export const FIND_RENT_SUCCESS = 'FIND_RENT_SUCCESS';
export const FIND_RENT_FAILURE = 'FIND_RENT_FAILURE';
